"""HTML scan report writer (Jinja2)."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from agentarmor.core.models import Finding, Scan, Severity
from agentarmor.reporting.owasp import rule_name

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>AgentArmor Scan Report — {{ scan.id }}</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 2rem; color: #1a1a1a; line-height: 1.5; }
    h1, h2 { color: #0f172a; }
    .meta { color: #64748b; font-size: 0.9rem; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
    .card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; background: #f8fafc; }
    .card strong { display: block; font-size: 1.5rem; }
    .severity-CRITICAL { color: #dc2626; }
    .severity-HIGH { color: #ea580c; }
    .severity-MEDIUM { color: #ca8a04; }
    .severity-LOW { color: #2563eb; }
    .severity-INFO { color: #64748b; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; }
    .owasp-tag { display: inline-block; background: #e0e7ff; color: #3730a3; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.8rem; margin-right: 0.25rem; }
    .evidence { font-family: monospace; font-size: 0.85rem; background: #f8fafc; padding: 0.5rem; border-radius: 4px; white-space: pre-wrap; }
    footer { margin-top: 2rem; color: #94a3b8; font-size: 0.85rem; }
  </style>
</head>
<body>
  <h1>AgentArmor Security Scan Report</h1>
  <p class="meta">Scan ID: {{ scan.id }} · Target: {{ target_label }} · Status: {{ scan.status.value }}</p>

  <h2>Executive Summary</h2>
  <p>
    AgentArmor executed <strong>{{ scan.probe_count }}</strong> security probes against
    <strong>{{ target_label }}</strong> and identified
    <strong class="severity-{{ worst_severity }}">{{ scan.finding_count }}</strong> finding(s).
    {% if scan.finding_count == 0 %}
    No security issues were detected at configured thresholds.
    {% else %}
  Highest severity observed: <strong class="severity-{{ worst_severity }}">{{ worst_severity }}</strong>.
    {% endif %}
  </p>

  <div class="summary-grid">
    <div class="card"><strong>{{ scan.probe_count }}</strong> Probes run</div>
    <div class="card"><strong>{{ scan.finding_count }}</strong> Findings</div>
    {% for sev, count in severity_counts %}
    <div class="card"><strong class="severity-{{ sev }}">{{ count }}</strong> {{ sev }}</div>
    {% endfor %}
  </div>

  <h2>OWASP Coverage</h2>
  <ul>
    {% for tag, count in owasp_counts %}
    <li><span class="owasp-tag">{{ tag }}</span> {{ owasp_names.get(tag, tag) }} — {{ count }} finding(s)</li>
    {% endfor %}
    {% if not owasp_counts %}
    <li>No OWASP-tagged findings.</li>
    {% endif %}
  </ul>

  <h2>Technical Findings</h2>
  {% if findings %}
  <table>
    <thead>
      <tr>
        <th>Issue</th>
        <th>Severity</th>
        <th>OWASP</th>
        <th>Risk</th>
        <th>Evidence</th>
      </tr>
    </thead>
    <tbody>
      {% for f in findings %}
      {% set e = f.metadata.get('enrichment', {}) if f.metadata else {} %}
      <tr>
        <td>{{ e.get('plain_title') or f.probe_name }}<br><span class="meta">{{ f.probe_id }}</span></td>
        <td class="severity-{{ f.severity.value }}">{{ f.severity.value }}</td>
        <td>{% for t in f.owasp %}<span class="owasp-tag">{{ t }}</span>{% endfor %}</td>
        <td>{{ "%.2f"|format(f.risk_score) }}</td>
        <td>
          {% if f.evidence %}
          <div class="evidence">{{ f.evidence[:3]|join("\\n") }}</div>
          {% endif %}
          {% if f.response_excerpt %}
          <div class="evidence">Response: {{ f.response_excerpt[:300] }}</div>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <h2>Issue details</h2>
  {% for f in findings %}
  {% set e = f.metadata.get('enrichment', {}) if f.metadata else {} %}
  {% if e %}
  <div class="card" style="margin-bottom:1rem;">
    <h3>{{ e.get('plain_title') or f.probe_name }}</h3>
    {% if e.get('what_happened') %}<p><strong>What happened:</strong> {{ e.what_happened }}</p>{% endif %}
    {% if e.get('why_it_matters') %}<p><strong>Why it matters:</strong> {{ e.why_it_matters }}</p>{% endif %}
    {% if e.get('remediation') %}
    <p><strong>Remediation:</strong></p>
    <ul>{% for r in e.remediation %}<li>{{ r }}</li>{% endfor %}</ul>
    {% endif %}
    {% if e.get('agentic_notes') %}<p><strong>AI analyst notes:</strong> {{ e.agentic_notes }}</p>{% endif %}
  </div>
  {% endif %}
  {% endfor %}
  {% else %}
  <p>No findings to report.</p>
  {% endif %}

  <footer>Generated by AgentArmor {{ version }}</footer>
</body>
</html>
"""


def _target_label(scan: Scan) -> str:
    t = scan.target
    if t.type.value == "endpoint":
        return t.url or "endpoint"
    if t.type.value == "provider":
        return f"provider:{t.provider}"
    if t.type.value == "local":
        return f"local:{t.model}"
    return t.type.value


def _worst_severity(findings: list[Finding]) -> str:
    order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    found = {f.severity for f in findings}
    for sev in order:
        if sev in found:
            return sev.value
    return Severity.INFO.value


def write_html_report(
    scan: Scan,
    findings: list[Finding],
    output_path: Path,
    *,
    version: str = "0.4.0",
) -> Path:
    from jinja2 import Template

    sev_counter = Counter(f.severity.value for f in findings)
    owasp_counter: Counter[str] = Counter()
    for f in findings:
        for tag in f.owasp:
            owasp_counter[tag] += 1

    owasp_names = {tag: rule_name(tag) for tag in owasp_counter}

    html = Template(_HTML_TEMPLATE).render(
        scan=scan,
        findings=findings,
        target_label=_target_label(scan),
        worst_severity=_worst_severity(findings),
        severity_counts=sorted(sev_counter.items(), key=lambda x: x[0]),
        owasp_counts=sorted(owasp_counter.items()),
        owasp_names=owasp_names,
        version=version,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return output_path
