"""PDF executive summary report (reportlab)."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from agentarmor.core.models import Finding, Scan, Severity
from agentarmor.reporting.owasp import rule_name


def write_pdf_report(
    scan: Scan,
    findings: list[Finding],
    output_path: Path,
    *,
    version: str = "0.5.0",
) -> Path:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(output_path), pagesize=letter)
    styles = getSampleStyleSheet()
    story: list = []

    target = _target_label(scan)
    story.append(Paragraph("AgentArmor Security Scan Report", styles["Title"]))
    story.append(Paragraph(f"Scan ID: {scan.id}", styles["Normal"]))
    story.append(Paragraph(f"Target: {target}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(
        Paragraph(
            f"Executed {scan.probe_count} probes. Found {scan.finding_count} issue(s). "
            f"Highest severity: {_worst_severity(findings)}.",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 12))

    sev_counts = Counter(f.severity.value for f in findings)
    if sev_counts:
        data = [["Severity", "Count"]] + [[k, str(v)] for k, v in sorted(sev_counts.items())]
        table = Table(data, hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 12))

    story.append(Paragraph("Top Findings", styles["Heading2"]))
    for f in findings[:10]:
        owasp = ", ".join(f"{t} ({rule_name(t)})" for t in f.owasp)
        story.append(Paragraph(f"<b>{f.probe_name}</b> — {f.severity.value}", styles["Normal"]))
        story.append(Paragraph(f"OWASP: {owasp}", styles["Normal"]))
        story.append(Paragraph(f.risk_score and f"Risk: {f.risk_score:.2f}" or "", styles["Normal"]))
        if f.response_excerpt:
            excerpt = f.response_excerpt[:200].replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(f"Evidence: {excerpt}", styles["Code"]))
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Generated by AgentArmor {version}", styles["Normal"]))
    doc.build(story)
    return output_path


def _target_label(scan: Scan) -> str:
    t = scan.target
    if t.type.value == "endpoint":
        return t.url or "endpoint"
    if t.type.value == "agent":
        return f"agent:{t.agent_framework}"
    if t.type.value == "mcp":
        return f"mcp:{t.mcp_target}"
    if t.type.value == "rag":
        return f"rag:{t.rag_corpus}"
    if t.type.value == "provider":
        return f"provider:{t.provider}"
    if t.type.value == "local":
        return f"local:{t.model}"
    return t.type.value


def _worst_severity(findings: list[Finding]) -> str:
    order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    found = {f.severity for f in findings}
    for sev in order:
        if sev in found:
            return sev.value
    return Severity.INFO.value
